name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install 32-bit development libraries
        run: |
         sudo dpkg --add-architecture i386
         sudo apt-get update
         sudo apt-get install -y \
         gcc-multilib g++-multilib \
         flex bison pkg-config \
         libx11-dev:i386 \
         libxext-dev:i386 \
         libxrender-dev:i386 \
         libxi-dev:i386 \
         libxrandr-dev:i386 \
         libxinerama-dev:i386 \
         libxcursor-dev:i386 \
         libxcomposite-dev:i386 \
         libxfixes-dev:i386 \
         libfreetype6-dev:i386 

      - name: Configure
        run: |
          mkdir build
          cd build
          ../configure

      - name: Build
        run: |
          cd build
          make -j$(nproc)
