name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y gcc-multilib g++-multilib

      - name: Configure
        run: |
          mkdir build
          cd build
          ../configure

      - name: Build
        run: |
          cd build
          make -j$(nproc)
